# SakuraTags Configuration

format_chat:
  enabled: true
  format: '{sakura_tag}{player}: {message}'

gui:
  title: '&d&lSelect a Tag!'

  tag_select_item:
    material: LIME_DYE
    displayname: '%tag_displayname%' # Placeholder for the tag display name
    lore:
      - '%tag_description%'          # Placeholder for tag description

  restricted_item:
    material: GRAY_DYE
    displayname: '&cLocked Tag'
    lore:
      - '&7You do not have permission to use this tag.'

  filler_item:
    material: MAGENTA_STAINED_GLASS_PANE
    displayname: ' '

  next_page:
    material: PAPER
    displayname: '&eNext Page'
    lore:
      - '&7Go to the next page of tags'

  previous_page:
    material: PAPER
    displayname: '&ePrevious Page'
    lore:
      - '&7Return to the previous page of tags'