################################ SAKURA-TAGS ################################
#
#  ___.                  __      _____         __        .___
#  \_ |_________   ____ |  | ___/ ____\_______/  |_    __| _/_______  __
#   | __ \_  __ \_/ __ \|  |/ /\   __\/  ___/\   __\  / __ |/ __ \  \/ /
#   | \_\ \  | \/\  ___/|    <  |  |  \___ \  |  |   / /_/ \  ___/\   /
#   |___  /__|    \___  >__|_ \ |__| /____  > |__|   \____ |\___  >\_/
#       \/            \/     \/           \/              \/    \/
#
#              SakuraTags - Author: brekfst - Version: 1.0
#
###############################################################################

format_chat:
  enabled: false
  format: '{sakura_tag}{player}: {message}'

gui:
  title: '&d&lSelect a Tag!'

  tag_select_item:
    material: NAME_TAG
    displayname: '%tag_displayname%'  # Placeholder for the tag display name
    lore:
      - '%tag_description%'           # Placeholder for tag description

  restricted_item:
    material: BARRIER
    displayname: '&cLocked Tag'
    lore:
      - '&7You do not have permission to use this tag.'

  filler_item:
    material: GRAY_STAINED_GLASS_PANE
    displayname: ' '

  next_page:
    material: PAPER
    displayname: '&eNext Page'
    lore:
      - '&7Go to the next page of tags'

  previous_page:
    material: PAPER
    displayname: '&ePrevious Page'
    lore:
      - '&7Return to the previous page of tags'