# SakuraTags Configuration

force_tags: false
check_updates: true
legacy_hex: false
papi_chat: true

format_chat:
  enabled: true
  format: '{sakura_tag} %1$s: %2$s'

gui:
  title: '&d&lSelect a Tag!'
  tag_select_item:
    material: NAME_TAG
    displayname: '%tag_displayname%'
    lore:
      - '%tag_description%'
  restricted_item:
    material: GRAY_DYE
    displayname: 'Locked Tag'
    lore:
      - 'You do not have permission to use this tag.'
  filler_item:
    material: BLACK_STAINED_GLASS_PANE
    displayname: ' '
  has_tag_item:
    material: PLAYER_HEAD
    displayname: 'Current tag: <white>%tag_displayname%'
    lore:
      - 'Click to remove your current tag'
  next_page:
    material: PAPER
    displayname: 'Next Page'
    lore:
      - 'Go to the next page of tags'
  previous_page:
    material: PAPER
    displayname: 'Previous Page'
    lore:
      - 'Return to the previous page of tags'
